spring:
  cloud:
    gateway:
      routes:
        - id: one
          uri: lb://MICROSERVICE-ONE
          predicates:
            - Path=/one/**
        - id: two
          uri: lb://MICROSERVICE-TWO
          predicates:
            - Path=/two/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka
